//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircompany
    {
        public int IDAircompany { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<int> Rating { get; set; }
        public string FactAdress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> YearOfCreate { get; set; }
    }
}
