//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirplaneModel
    {
        public int NumberModel { get; set; }
        public string Decoding { get; set; }
        public Nullable<int> CountSeats { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> LenghtFly { get; set; }
        public Nullable<int> MaxWeight { get; set; }
        public string MaxHeight { get; set; }
    }
}
